spring:
  datasource:
    url: jdbc:postgresql://db:5432/workoutapp
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:workout}
    password: ${DB_PASSWORD:workout_secret}
    hikari:
      connection-timeout: 30000
      initialization-fail-timeout: 60000
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  h2:
    console:
      enabled: false
