apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: workout
  namespace: workout
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
    - host: workout.pablogeorge.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: workout
                port:
                  number: 8080
